<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1713210841391' stop='1713210841509'>
    <name>Авторизация</name>
    <title>Авторизация</title>
    <test-cases>
        <test-case start='1713210841391' status='failed' stop='1713210841504'>
            <name>Создание пользователя</name>
            <title>Создание пользователя</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: getaddrinfo ENOTFOUND bookstore.demoqa.comaccount</message>
                <stack-trace>Error: getaddrinfo ENOTFOUND bookstore.demoqa.comaccount
                    at Function.Object.&lt;anonymous>.AxiosError.from (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\core\AxiosError.js:89:14)
                    at RedirectableRequest.handleRequestError (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\adapters\http.js:610:25)
                    at RedirectableRequest.emit (node:events:513:28)
                    at ClientRequest.eventHandlers.&lt;computed> (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\follow-redirects\index.js:38:24)
                    at ClientRequest.emit (node:events:513:28)
                    at TLSSocket.socketErrorListener (node:_http_client:502:9)
                    at TLSSocket.emit (node:events:513:28)
                    at emitErrorNT (node:internal/streams/destroy:151:8)
                    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                    at processTicksAndRejections (node:internal/process/task_queues:82:21)
                    at Axios.request (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\core\Axios.js:45:41)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)
                    at Object.createUser [as create] (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\HomeWork\lesson_8\pageobjects\UserService.js:19:20)
                    at Object.&lt;anonymous> (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\HomeWork\lesson_8\spec\lesson8.spec.js:14:30)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1713210841504' status='failed' stop='1713210841509'>
            <name>Авторизация</name>
            <title>Авторизация</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: getaddrinfo ENOTFOUND bookstore.demoqa.comaccount</message>
                <stack-trace>Error: getaddrinfo ENOTFOUND bookstore.demoqa.comaccount
                    at Function.Object.&lt;anonymous>.AxiosError.from (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\core\AxiosError.js:89:14)
                    at RedirectableRequest.handleRequestError (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\adapters\http.js:610:25)
                    at RedirectableRequest.emit (node:events:513:28)
                    at ClientRequest.eventHandlers.&lt;computed> (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\follow-redirects\index.js:38:24)
                    at ClientRequest.emit (node:events:513:28)
                    at TLSSocket.socketErrorListener (node:_http_client:502:9)
                    at TLSSocket.emit (node:events:513:28)
                    at emitErrorNT (node:internal/streams/destroy:151:8)
                    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                    at processTicksAndRejections (node:internal/process/task_queues:82:21)
                    at Axios.request (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\node_modules\axios\lib\core\Axios.js:45:41)
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)
                    at Object.authorized (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\HomeWork\lesson_8\pageobjects\UserService.js:59:20)
                    at Object.&lt;anonymous> (C:\Users\user\Desktop\HW-8\Lessons-testing_library_5\HomeWork\lesson_8\spec\lesson8.spec.js:20:30)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>